- include_vars: vault.yml

- name: Install required mosquitto packages
  apt: name={{item}} state=installed
  become: yes
  with_items:
      - mosquitto

- name: mosquitto config file
  template: dest=/etc/mosquitto/mosquitto.conf src=../templates/mosquitto.conf
  become: yes

  # Password set manually like this:
  # sudo mosquitto_passwd -c /etc/mosquitto/passwd mosquitto